name: Forms Flow BPM CI
on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - master
      - release/**
      - trivy
  pull_request:
    branches:
      - develop
      - master
      - release/**
    paths:
      - "forms-flow-bpm/**"

defaults:
  run:
    shell: bash
    working-directory: ./forms-flow-bpm

jobs:
  setup-job:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - run: "true"
  Test:
    if: always()
    needs: setup-job
    runs-on: ubuntu-20.04
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Cache Maven packages
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Run Tests
        run: mvn -B test --file pom.xml
  Build:
    if: always()
    needs: setup-job
    runs-on: ubuntu-20.04
    name: Build
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build . -t forms-flow-bpm
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'forms-flow-bpm'
          format: 'sarif'
          output: 'trivy-results.sarif'
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

